---
title: <span style="color:blue">Bibliografía</span>

---
<p align="justify">
\
Acosta, M., & Mugica, L. (1992). Ciclo de vida del Sabanero (Sturnella magna)(Aves: Icteridae) en el Jardín Botánico Nacional. Revista del Jardín Botánico Nacional, 123-128.
\
\
Contreras-Balderas, A. J., Ayala, C. D. J. M. T., Stephano, M. M. A. S., Páez, B. H. G., Medrano, B. O. B., de Leija, B. A. C., ... & Castro, J. C. G. S. (2015)  MONITOREO DE AVES DE PASTIZAL EN EL ÁREA DE PROTECCIÓN DE FLORA Y FAUNA MADERAS DEL CARMEN, COAHUILA, MÉXICO
\
\
Dickerman, R. W., & Phillips, A. R. (1970). Taxonomy of the common meadowlark (Sturnella magna) in central and southern México and Caribbean Central America. Condor, 305-309.
\
\
Gutiérrez, A. (2003). Caracterización preliminar de la avifauna del parque Entrenubes y pautas para su conservación. Fundación SUNAHISCA.
\
\
Inder. (2016) Región Central caracterización del territorio Cartago-Oreamuno-El Guarco-La Unión. Inder, 6-10.
\
\
Kershner, E. L., Walk, J. W., & Warner, R. E. (2004). Postfledging Movements and Survival of Juvenile Eastern Meadowlarks (Sturnella magna) in Illinois. The Auk, 1146-1154.
\
\
 Martinka B.2014. Western_Meadowlark (Sturnella magna). In: Poole A, editor. The birds of North America online. Cornell Lab of Ornithology (Ithaca, NY). http: /allaboutbirds.org/guide/Western_Meadowlark
\
\
Robinson W. 2012. Summer Tanager (Piranga rubra). In: Poole A, editor. The birds of North America online. Cornell Lab of Ornithology (Ithaca, NY). http://bna.birds.cornell.edu. bnaproxy.birds.cornell.edu/bna/species/248
\
\
Smith K., Neal J. & Mlodinow M.  (2016) "Unusual Concentration of Summer Tanagers (Piranga rubra) in Northwestern Arkansas during Winter 2015-2016," Journal of the Arkansas Academy of Science 70 (52), 292-294.
 \
 \
M. Shepherd, T., & J. Burns, K. (2007). Intraspecific genetic analysis of the summer tanager Piranga rubra: implications for species limits and conservation. Journal of Avian Biology, 38(1), 13-27.
\
\
Holden B. & Burrell K. (2015).Foraging by a Summer Tanager during a reorientation flight. Ontario´s Birds, 33(3), 83-85.
<p>





